//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::contact::Entity as Contact;
pub use super::entity::Entity;
pub use super::ppl::Entity as Ppl;
pub use super::r#trait::Entity as Trait;
pub use super::relation::Entity as Relation;
pub use super::sig_date::Entity as SigDate;
pub use super::tier::Entity as Tier;
