//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "relation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ppl_id_a: i32,
    pub ppl_id_b: i32,
    pub r#type: String,
    pub date_entered: Date,
    pub date_ended: Date,
    pub superseded: bool,
    pub date_ins: Date,
    pub date_up: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
