//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sig_date")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ppl_id: i32,
    pub date: Date,
    pub event: String,
    pub do_remind: bool,
    pub with_ppl: Json,
    pub date_ins: Date,
    pub date_up: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
